
# Note: this file's config overrides the Netlify UI admin config

# /!\ due to using a monorepo it can be a bit messy to configure Netlify
# See also https://github.com/netlify/build/issues/2483

[build]
  command = "yarn build"
  publish = "website/build"

[build.environment]
  NODE_VERSION = "14"

[context.production]
  command = "yarn netlify:build:production"

[context.deploy-preview]
  command = "yarn netlify:build:deployPreview"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [
    "node_modules/.cache/webpack",
  ]
