module.exports = {
  docs: [
    {type: 'autogenerated', dirName: '.'},
  //   {
  //     type: 'category',
  //     label: 'API Reference',
  //     collapsible: true,
  //     collapsed: false,
  //     items: [
  //       {
  //         type: 'category',
  //         label: 'REST API',
  //         collapsible: true,
  //         collapsed: false,
  //         items: [
  //           {
  //             type: 'link',
  //             label: 'v1',
  //             href: '/api/?v=v1',
  //           },
  //           {
  //             type: 'link',
  //             label: 'v2',
  //             href: '/api/?v=v2',
  //           },
  //         ],
  //       }
  //     ],
  //   }
  ],
};
