/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
  community: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      href: 'https://github.com/syntixi/syntixi/issues/new?assignees=&labels=&template=feature_request.md&title=',
      label: 'Feature Requests',
    },
    {
      type: 'link',
      label: 'Help',
      href: 'https://github.com/syntixi/syntixi',
    },
  ],
};
